### ISSUE TITLE
EventNode Usecase

### ISSUE THREAD

**Issue by wolfeytlycan** [ShenKSPZ/PlayText#1]
Hello! I recently purchased this asset and plan to use it for my upcoming game. 

I am new to Unity's event system, and listeners in general.

You mention the use of EventNodes in the marketing and are available in graph view, but provide no documentation for them.

How would one go about using an event node to call another method?

Thank you.

**Comment by ShenKSPZ** [comment]
Hello,&nbsp;


Thanks for your purchasing. I will update the document recently. Here is a video tutorial about how to use event node.&nbsp;https://youtu.be/MC3xBnLVmJk. (Start at 7:48)&nbsp;


Best regards,
Lawrence Peng



---Original---

**Comment by wolfeytlycan** [comment]
Thank you so much! This was incredibly helpful, and would be a very welcome addition to the documentation!

**Comment by wolfeytlycan** [comment]
Hello! Sorry to reopen the issue, but all EventNodes created in a new Graph cause the game to fully hang/crash when they are reached.

This only happens when the graph is created within a certain project. my main project. If it is created in any other project it works just fine.

**Comment by ShenKSPZ** [comment]
Hello,


Could you please give me a screenshot of your unity's console when it crash? Or copy the error message.&nbsp;


Thank you!
Lawrence Peng



---Original---

**Comment by wolfeytlycan** [comment]
it doesn't provide a console crash, it just hangs, like it's stuck in an infinite while loop.

**Comment by ShenKSPZ** [comment]
Could you give me screenshot of your graph and the code that receive the event node?&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by wolfeytlycan** [comment]
I apologize for the delay. The issue is definitely in EventNode.cs MoveNext() and returning itself if there is not another node linked after it. The while loop in DialogueGraph.cs Continue() line 50 never terminates. 

For now I've just made it return null because I'm also setting the current graph to null once FinishTalking is invoked

**Comment by ShenKSPZ** [comment]
I already update a new version to fix this bug.
